---
- hosts: localhost
  become: true
  vars:
    terraform:
      version: 1.5.7
      checksum: sha256:c0ed7bc32ee52ae255af9982c8c88a7a4c610485cf1d55feeb037eab75fa082c
    docker_compose:
      version: 1.25.3
    clj:
      version: 1.11.3.1463
    flyway:
      version: 8.2.2
      checksum: sha1:f032847a4a91bf4b3878cdb59b7d12b7f64ed0cc
    aws_vault:
      version: 7.2.0
  roles:
    - role: apt-repos
      tags: [apt, apt-repos]
      repos:
        - name: signal-desktop
          key_url: https://updates.signal.org/desktop/apt/keys.asc
          repo: deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main
        - name: docker
          key_url:  https://download.docker.com/linux/ubuntu/gpg
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        - name: kopia
          key_url: https://kopia.io/signing-key
          repo: deb http://packages.kopia.io/apt/ stable main
    - role: aws-cli
      tags: [aws, aws-cli]
    - role: aws-cdk
      tags: [aws, aws-cdk]
    - role: google-cloud-sdk
      tags: [gcloud]
    - role: golang
      version: 1.22.2
      checksum: sha256:5901c52b7a78002aeff14a21f93e0f064f74ce1360fce51c6ee68cd471216a17
      make_default: true
      clean: true
      tags: [golang]
    - role: packer
      tags: [packer]
      packer:
        version: 1.9.5
        checksum: sha256:6f8272658a6d606583c2b3deaad272233db6e84a6ee651bf17a0d46d8cea4a9c
    - role: gopass
      tags: [gopass]
  tasks:
    - name: Set timezone
      ansible.builtin.timezone:
        name: Europe/London
      tags:
        - system
    - name: Remove Tutanota Desktop
      ansible.builtin.file:
        path: /usr/local/bin/tutanota
        state: absent
      tags:
        - cleanup
    - name: Remove redundant APT packages
      ansible.builtin.apt:
        package:
          - nodejs                    # installed via snap
          - openvpn
          - openvpn-systemd-resolved
          - openjdk-8-jdk
          - pass                      # prefer gopass
        state: absent
        autoremove: true
      tags:
        - apt
    - name: Install packages from APT
      ansible.builtin.apt:
        package:
          - age
          - asciinema
          - certbot
          - cl-quicklisp
          - clamav-daemon
          - cmake
          - containerd.io
          - curl
          - dict
          - docker-ce
          - docker-ce-cli
          - firetools
          - fonts-powerline
          - git
          - git-lfs
          - graphviz
          - gufw
          - imagemagick-6.q16
          - jq
          - keepassx
          - kopia
          - libpostgresql-jdbc-java
          - libtool
          - libvterm0
          - libvterm-bin
          - libvterm-dev
          - net-tools
          - nmap
          - openjdk-11-jdk
          - openssl
          - podman
          - postgresql-client-14
          - pre-commit
          - pwgen
          - python3-pip
          - python3-pytest
          - python3-yapf
          - python3-venv
          - rlwrap
          - sbcl
          - signal-desktop
          - tree
          - uuid
          - virt-manager
          - wait-for-it
          - yamllint
      tags:
        - apt
        - apt-install
    - name: Install git-credential-gopass
      ansible.builtin.apt:
        deb: https://github.com/gopasspw/git-credential-gopass/releases/download/v1.15.13/git-credential-gopass_1.15.13_linux_amd64.deb
    - name: Download flyway {{flyway.version}}
      ansible.builtin.get_url:
        url: https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/{{flyway.version}}/flyway-commandline-{{flyway.version}}-linux-x64.tar.gz
        checksum: "{{flyway.checksum}}"
        dest: /var/tmp/flyway-commandline-{{flyway.version}}-linux-x64.tar.gz
      register: flyway_archive
      tags:
        - archives
        - flyway
    - name: Extract flyway {{flyway.version}}
      ansible.builtin.unarchive:
        src: "{{flyway_archive.dest}}"
        dest: /usr/local
      tags:
        - archives
        - flyway
    - name: Fix flyway executable permissions
      ansible.builtin.file:
        path: /usr/local/flyway-{{flyway.version}}/flyway
        mode: 0755
      tags:
        - flyway
    - name: Create symlink to flyway executable
      ansible.builtin.file:
        path: /usr/local/bin/flyway
        state: link
        src: /usr/local/flyway-{{flyway.version}}/flyway
      tags:
        - flyway
    - name: Download terraform {{terraform.version}}
      ansible.builtin.get_url:
        url: https://releases.hashicorp.com/terraform/{{terraform.version}}/terraform_{{terraform.version}}_linux_amd64.zip
        checksum: "{{terraform.checksum}}"
        dest: /var/tmp/terraform_{{terraform.version}}_linux_amd64.zip
      register: tf_archive
      tags:
        - archives
        - terraform
    - name: Install terraform {{terraform.version}}
      unarchive:
        src: "{{tf_archive.dest}}"
        dest: /usr/local/bin/
        creates: /usr/local/bin/terraform
      tags:
        - archives
        - terraform
    - name: Fetch and install docker-compose {{docker_compose.version}}
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/{{docker_compose.version}}/docker-compose-{{ansible_system}}-{{ansible_architecture}}
        dest: /usr/local/bin/docker-compose
        owner: root
        group: root
        mode: 0755
      tags:
        - archives
    - name: Add ray to docker group
      ansible.builtin.user:
        name: ray
        groups:
          - docker
        append: True
      tags:
        - system
    - name: Add ray to libvirt group
      ansible.builtin.user:
        name: ray
        groups:
          - libvirt
        append: True
      tags:
        - system
    - name: Create /usr/local/lib/java
      ansible.builtin.file:
        path: /usr/local/lib/java
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: Download Clojure {{clj.version}}
      ansible.builtin.get_url:
        url: https://download.clojure.org/install/linux-install-{{clj.version}}.sh
        dest: /tmp/linux-install-{{clj.version}}.sh
        owner: root
        group: root
        mode: 0755
      tags:
        - clj
    - name: Install Clojure {{clj.version}}
      ansible.builtin.command: /tmp/linux-install-{{clj.version}}.sh
      tags:
        - clj
    - name: Download SchemaSpy
      ansible.builtin.get_url:
        url: https://github.com/schemaspy/schemaspy/releases/download/v6.1.0/schemaspy-6.1.0.jar
        dest: /usr/local/lib/java
      tags:
        - schemaspy
      register: schemaspy
    - name: Create SchemaSpy wrapper
      ansible.builtin.copy:
        dest: /usr/local/bin/schemaspy
        mode: 0755
        content: |
          #!/bin/bash
          exec java -jar {{schemaspy.dest}} "$@"
      tags:
        - schemaspy
    - name: Install Python packages
      ansible.builtin.pip:
        name:
          - boto
          - boto3
          - jwcrypto
          - powerline-shell
          - ruff
          - "python-lsp-server[all]"
        state: latest
      tags:
        - python
    - name: Install VSCode
      community.general.snap:
        name: code
        classic: True
      tags:
        - vscode
    - name: Install chezmoi
      community.general.snap:
        name: chezmoi
        classic: True
      tags:
        - chezmoi
    - name: Install Leiningen
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        dest: /usr/local/bin/lein
        mode: 0755
      tags:
        - lein
    - name: Install sqlc
      community.general.snap:
        name: sqlc
    - name: Remove closh
      ansible.builtin.file:
        path: /usr/local/lib/java/closh-zero.jar
        state: absent
    - name: Remove closh wrapper
      ansible.builtin.file:
        path: /usr/local/bin/closh
        state: absent
        owner: root
    - name: Install AWS vault v{{aws_vault.version}}
      ansible.builtin.get_url:
        url: https://github.com/99designs/aws-vault/releases/download/v{{aws_vault.version}}/aws-vault-linux-amd64
        dest: /usr/local/bin/aws-vault
        owner: root
        group: root
        mode: 0755
        backup: True
      tags:
        - aws-vault
    - name: Install Slack desktop
      community.general.snap:
        name:
          - slack
        channel: latest/stable
      tags:
        - slack
    - name: Install hoard
      ansible.builtin.apt:
        deb: "https://github.com/hyde46/hoard/releases/download/v1.4.2/hoard_1.4.2_amd64.deb"
      tags:
        - apt
        - hoard
    - name: Install halloy
      community.general.snap:
        name: halloy
      tags:
        - halloy
